function [deadReckX,deadReckY,deadReckTH,deadReckTime] = importDeadReck(path,filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DEADRECKX,DEADRECKY,DEADRECKTH,DEADRECKTIME] = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [DEADRECKX,DEADRECKY,DEADRECKTH,DEADRECKTIME] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [deadReckX,deadReckY,deadReckTH,deadReckTime] = importfile('dead_navigation.txt',1, 1190);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/12/11 12:36:28

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
filename=fullfile(path,filename)
fileID = fopen(filename,'r');


%%determine file size OBS detta är plattforms specifikt för windows
[status, cmdout] = system(['find /c /v "" ', filename]);
    if(status~=1)
        scanCell = textscan(cmdout,'%s %s %u');
        lineCount = scanCell{3};
        disp(['Found ', num2str(lineCount), ' lines in the file']);
    end
    endRow = lineCount;



%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
deadReckX = dataArray{:, 1};
deadReckY = dataArray{:, 2};
deadReckTH = dataArray{:, 3};
deadReckTime = dataArray{:, 4};


